### ISSUE TITLE
When plugin update to 1.21?

### ISSUE THREAD

**Issue by UltimateTrouble** [efeketket/PlayerShops#3]
Just asking when this will be updated to 1.21 or if it will be updated because I need it for my MC server.

**Comment by felixgorke** [comment]
also waiting for 1.21 :)

**Comment by efeketket** [comment]
Hey Felix

Thank you for your attention. Mojang has introduced many changes to datapacks, and I'm still trying to update my projects to the new version during my free times. In particular, the Player Shops datapack is quite challenging because it involves really complicated situations, and I'm stuck on it. Well, that will take a little while.

Thank you for your patience!

Let me know if you need further adjustments! Have a nice day.

Greetings
Efe
________________________________

**Comment by efeketket** [comment]
> Just asking when this will be updated to 1.21 or if it will be updated because I need it for my MC server.

Sorry for the delay. Im doing my best to update it.
